name = "Shard"
grammar = "scheme"
path_suffixes = ["shard"]
line_comments = [";; ", "; "]
tab_size = 2
autoclose_before = ";)"
# `case-on`, `rewrite-with`, `S^` are single words.
word_characters = ["-", "_", "^"]

brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
