#!/usr/bin/env python3
"""Generate examples/pio_vectors_data.shard from examples/pio_vectors.jsonl.

The jsonl is the committed copy of mlx-pio's 101 certified vectors
(shard_pio/vectors/shard_vectors.jsonl, emulator-certified; provenance in
docs/PIO.md §5). Output goes to stdout; the committed data file is the
shardfmt of this output, and run_corpus.sh carries a regen pin (re-generate,
re-format, byte-compare).

Emits DATA ONLY (PVec values + all_vecs) — the gate's claims are hand-written
in examples/pio_vecgate.shard.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
JSONL = os.path.join(HERE, "..", "..", "examples", "pio_vectors.jsonl")


def ilist(xs):
    return "(list " + " ".join(str(x) for x in xs) + ")" if xs else "Nil"


def b2i(v):
    return 1 if v else 0


def main():
    rows = [json.loads(line) for line in open(JSONL)]
    out = []
    out.append(
        ";;; pio_vectors_data.shard — GENERATED by tools/piovec/gen_vectors.py"
    )
    out.append(";;; from examples/pio_vectors.jsonl (mlx-pio's 101 certified")
    out.append(";;; vectors; docs/PIO.md §5-§6). DO NOT EDIT — regen pin in")
    out.append(";;; run_corpus.sh re-generates and byte-compares.")
    out.append("")
    out.append('(import "pio_vecrun.shard")')
    out.append("(use (:: examples pio_vecrun *))")
    out.append("(use (:: models pio pio *))")
    out.append("")
    names = []
    for i, r in enumerate(rows):
        assert len(r["inputs"]) <= 4, (i, "streaming leg unexercised")
        assert 1 <= r["push_threshold"] <= 32, (i, "threshold not normalized")
        assert 1 <= r["pull_threshold"] <= 32, (i, "threshold not normalized")
        opins = 0
        for p in r["output_pins"]:
            opins |= 1 << p
        cfg = " ".join(
            str(x)
            for x in [
                r["wrap_top"],
                r["wrap_bottom"],
                r["side_count"],
                b2i(r["side_en"]),
                b2i(r["side_pindir"]),
                r["sideset_base"],
                r["jmp_pin"],
                r["in_base"],
                0,  # in_count (absent from the jsonl schema: no masking)
                r["out_base"],
                r["out_count"],
                r["set_base"],
                r["set_count"],
                b2i(r["autopush"]),
                b2i(r["autopull"]),
                r["push_threshold"],
                r["pull_threshold"],
                b2i(r["in_shift_right"]),
                b2i(r["out_shift_right"]),
                r["clkdiv_int"],
                r["clkdiv_frac"],
                0,  # status_sel (absent: MOV STATUS compares TX level)
                0,  # status_n
                r["sm_id"],
                r["tx_depth"],
                r["rx_depth"],
            ]
        )
        names.append(f"(vec_{i})")
        out.append(f";; vector {i}: {r['name']}")
        out.append(f"(fn vec_{i} () PVec")
        out.append("  (MkPVec")
        out.append(f"    (MkPCfg Nil {cfg})")
        out.append(f"    {ilist(r['code'])}")
        out.append(f"    {ilist(r['inputs'])}")
        out.append(f"    {opins}")
        out.append(f"    {ilist(r['capture_pins'])}")
        out.append(f"    {r['stim_mask']}")
        out.append(f"    {ilist(r['stim_values'])}")
        out.append(f"    {ilist(r['trace'])}))")
        out.append("")
    out.append("(fn all_vecs () (List PVec)")
    out.append("  (list " + " ".join(names) + "))")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
